### PR TITLE
Ziwei/question component

### PR DESCRIPTION
**Pull request by hachilam92**
Achieved:
1. fix the issue of inconsistency of  displaying modal background and icons;
2. extract Avatar component to reuse it in Question;
3. add a footer for word-limit displaying and submit button;
4. add a feature of leaving questions under tasks;

Continuing:
1. add a feature of replying questions;
2. add marks on replies left by the poster;
3. add question counter;
4. add hiding-logic on questions and replies; 

Notice:
1. the question adding will be triggered twice under strict mode;

### CODE REVIEW

**Review by Changhong-st — APPROVED** [review]

**Review by JavaScriptN0ob — APPROVED** [review]

**Comment by JavaScriptN0ob** [comment]
做了测试吗，我看到CI亮了一条Checked

**Comment by hachilam92** [comment]
好像大潘加了一个自动测试

**Comment by JavaScriptN0ob** [comment]
晚点我问他一下，直接Merge吧

**Comment by hachilam92** [comment]
好的

**Comment by JavaScriptN0ob** [comment]
可能周三开始，我把eslintrc.js加上，目前代码有些部分还是不够工整。

**Pull request merged**
