### PR TITLE
Ziwei/create profile modal

### PR DESCRIPTION
**Pull request by hachilam92**
Achieved:
1. removed experimental code;
2. replace some private components (e.g. button) with the public ones;
3. adjust styles of some public components (e.g. remove outlines)
3. finish basic page layout and input logic of the profile creation modal

Continuing:
1. avatar uploading feature;
2. SMS check feature;
3. input validation;
4. state-check before submission;
5. modal layout and toggling;
6. profile page triggered by a button instead of  the temporary route;

### CODE REVIEW

**Review by JavaScriptN0ob — APPROVED** [review]
我看还是写了关于profile 的 Reducer了，我先帮你approve了。周三开会聊一下redux还有hooks的必要性吧。

**Comment by JavaScriptN0ob** [comment]
我看还是写了关于profile 的 Reducer了，我先帮你approve了。周三开会聊一下redux还有hooks的必要性吧。

**Comment by ttcode10** [comment]
Approved

**Review by ttcode10 — APPROVED** [review]
Approved

**Pull request merged**
